# core/plugin.py
from abc import ABC, abstractmethod

class Plugin(ABC):
    """Basic‑Class for all Plugins."""

    def __init__(self, app):
        self.app = app

    def on_init(self): ...
    def on_start(self): ...
    def on_event(self, event): ...
    def on_update(self, dt): ...
    def on_render(self, surface): ...
    def on_shutdown(self): ...
