screen:
  width: 800
  height: 600
  fps: 60
  title: SimShell Framework
paths:
  stats_config: setup/stats_config.json
  log_file: simshell.log
  plugins_path: plugins
logging:
  level: DEBUG
  file_level: DEBUG
  console_level: INFO
  max_bytes: 1000000
  backup_count: 3
  date_format: '%H:%M:%S'
  file_log_format: '%(asctime)s %(levelname)-5s [%(name)s] %(message)s'
  console_log_format: '%(levelname)-5s | %(message)s'
fonts:
  default:
    name: Arial
    size: 18
  debug:
    name: Consolas
    size: 12
  title:
    name: Arial Black
    size: 24
ui:
  default:
    border_width: 2
    padding: 5
    spacing: 10
  debug_console:
    max_lines: 10
    pos:
    - 10
    - 10
theme:
  default: dark
scenes:
  initial: menu
  available:
  - menu
  - game
  - plugin_manager
